# Default configuration for BioSIM web API 
VERBOSE = True
MULTIPROCESS_MODE = False
PRODUCTION_MODE = False
UPDATER_ENABLED = False
MINIMAL_CONFIG = True
NB_MAX_COORDINATES_NORMALS = 50
NB_MAX_COORDINATES_WG = 10
PORT = 5000
